# this is for using one play to do everything
# roles

---
- hosts: all
  become: true
  pre_tasks:
	  
	  - name: install updates (CentOS)
	    dnf:
			update_only: yes
			update_cache: yes
		changed_when: false
		when: ansible_distribution == "CentOS"
		
	  - name: Install Updates (Ubuntu)
	    apt:
			upgrade: dist
			update_cache: yes
		changed_when: false
		when: ansible_distribution == "Ubuntu"
		
# these are tasks for the websers only
- hosts: web_servers
  become: true
  tasks:
	  
# defining roles
- hosts: all
  become: true
  roles:
	  - base
	  
- hosts: web_servers
  become: true
  roles:
	  - web_servers
	  
- hosts: database_servers
  become: true
  roles:
	  - database_servers
	  
- hosts: file_servers
  become: true
  roles:
	  - file_servers
	  
- hosts: workstations
  become: true
  roles:
	  - workstations
	  
# then in main.yml in the directory for all the roles add the code you want them to run